name: Build lsfg-vk on Debian
on: [push]

jobs:
  build-debian:
    runs-on: ubuntu-latest
    container:
      image: debian:trixie
    steps:
    - name: Prepare cache for apt packages
      uses: actions/cache@v4
      with:
        path: /var/cache/apt/archives
        key: debian-apt-cache
    - name: Install build dependencies
      run: |
        export DEBIAN_FRONTEND=noninteractive
        apt-get update
        apt-get install -y \
          build-essential \
          clang clang-tools llvm \
          git tar \
          cmake ninja-build \
          spirv-headers libvulkan-dev
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Configure with CMake and Ninja
      run: |
        cmake -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=./build-release
    - name: Build with Ninja
      run: |
        ninja -C build
    - name: Install with CMake
      run: |
        cmake --install build
    - name: Upload lsfg-vk artifact
      uses: actions/upload-artifact@v4
      with:
        name: lsfg-vk_debian
        path: |
          build-release/share/vulkan/implicit_layer.d/VkLayer_LS_frame_generation.json
          build-release/lib/liblsfg-vk.so
