name: Update lsfg-vk Flatpak (23.08)
on:
  push:
    branches: ["develop", "flatpak"]

jobs:
  update-flatpak:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-23.08
      options: --privileged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build Flatpak extension
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: "org.freedesktop.Platform.VulkanLayer.lsfg_vk"
          manifest-path: "flatpak/org.freedesktop.Platform.VulkanLayer.lsfgvk_23.08.yml"
          verbose: true
